server:
  servlet:
    context-path: /mao
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_mao?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
        location: /static/upload
        enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

